version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  service:
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./service:/app
      - /app/node_modules
